### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by samarth51** [InstitutCurie/SV-Bay#2]
Hi,
I am trying to run example data using conf.yaml provided within SV-Bay package. I have changed all essential paths but facing an error during program execution. Can you please look into this problem.  
Command:
python -B src/main_clustering.py -c config/config.yaml

Traceback (most recent call last):
  File "../SV-Bay-master/src/main_clustering.py", line 96, in <module>
    stats_temp_file = open(stats_temp_fname, 'r')
IOError: [Errno 2] No such file or directory: '/tmp/stats_chr13.tmp'

Thanks 
Samarth Kulshrestha

**Comment by dashainparis** [comment]
Hello, Samarth!

it seems that you do not have bam file for chr13. In
folder working_dir/sam_files_dir/ should be bam files split by chromosome.
If you do not want to perform analysis in chromosome 13, you should delete
it from the list of the chromosomes in field 'chromosomes :' in config file.

Hope it would help!

2016-04-07 16:23 GMT+03:00 Samarth Kulshrestha notifications@github.com:

> Hi,
> I am trying to run example data using conf.yaml provided within SV-Bay
> package. I have changed all essential paths but facing an error during
> program execution. Can you please look into this problem.
> 
> Command:
> python -B src/main_clustering.py -c config/config.yaml
> 
> Traceback (most recent call last):
> File "../SV-Bay-master/src/main_clustering.py", line 96, in
> stats_temp_file = open(stats_temp_fname, 'r')
> IOError: [Errno 2] No such file or directory: '/tmp/stats_chr13.tmp'
> 
> Thanks
> Samarth Kulshrestha
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/InstitutCurie/SV-Bay/issues/2

## 

Best regards,

Iakovishina Daria

**Comment by samarth51** [comment]
Thanks for your quick response. Yes, you point it right that i do not have bam for chr13 and i made it correct by editing my config.yaml file. But again i face trouble when i execute the edited version of my config file. 
Error says: 

File "scipy/cluster/_vq.pyx", line 340, in scipy.cluster._vq.update_cluster_means (scipy/cluster/_vq.c:4654)
TypeError: type other than float or double not supported

Can you please look into this new error..

Thanks again.
Samarth Kulshrestha

**Comment by dashainparis** [comment]
Hi Samarth,

I think it's something wrong with version of python or scipy, can you show
me which version do you use.

Did you try to run SV-Bay on test data?

2016-04-08 9:14 GMT+03:00 Samarth Kulshrestha notifications@github.com:

> Thanks for your quick response. Yes, you point it right that i do not have
> bam for chr13 and i made it correct by editing my config.yaml file. But
> again i face trouble when i execute the edited version of my config file.
> Error says:
> 
> File "scipy/cluster/_vq.pyx", line 340, in
> scipy.cluster._vq.update_cluster_means (scipy/cluster/_vq.c:4654)
> TypeError: type other than float or double not supported
> 
> Can you please look into this new error..
> 
> Thanks again.
> Samarth Kulshrestha
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/InstitutCurie/SV-Bay/issues/2#issuecomment-207234395

## 

Best regards,

Iakovishina Daria

**Comment by samarth51** [comment]
Actually i am trying to set up a run on SV-Bay test data itself. 
Version information:
Python version 2.7.7
Scipy version 0.17.0

**Comment by sailepradh** [comment]
Hi,

I too am running into similar error while running command in the test data-set. Seems like the kmeans from scipy.cluster.vq.kmeans implementation is causing the trouble as seen in here  http://stackoverflow.com/questions/34084142/python-3-most-common-color-in-image-kmeans-data-type-match but really don't know how to implement in the cluster.py script.

Regards,
Saile

**Comment by jungminchoilab** [comment]
Hello,

I am running into the same error message. Did any of you guys solve it?

Thanks,
Jungmin

```
Traceback (most recent call last):
  File "/home/jc2545/programs/SV-Bay/src/main_clustering.py", line 89, in <module>
    Process(data_file, config)
  File "/home/jc2545/programs/SV-Bay/src/main_clustering.py", line 80, in Process
    cf.PerformClustering()
  File "/ycga-ba/home/jc2545/programs/SV-Bay/src/chrfragments.py", line 175, in PerformClustering
    utils.clust(self.fr_abn, self.chr, 'fr', self.biggest_normal, self.smallest_normal, self.config, self.flag_direction)
  File "/ycga-ba/home/jc2545/programs/SV-Bay/src/utils.py", line 65, in clust
    clusters = cluster.Clustering(fragments, M, S, chrm, chrm, 0, config,direction)
  File "/ycga-ba/home/jc2545/programs/SV-Bay/src/cluster.py", line 414, in Clustering
    new_clusters = KMeansSplit(cluster_for_kmeans, D)
  File "/ycga-ba/home/jc2545/programs/SV-Bay/src/cluster.py", line 342, in KMeansSplit
    (res_my, idx_my) = kmeans2(array(zip(x)), k)
  File "/home/jc2545/.local/lib/python2.7/site-packages/scipy/cluster/vq.py", line 772, in kmeans2
    return _kmeans2(data, clusters, iter, nc, _valid_miss_meth[missing])
  File "/home/jc2545/.local/lib/python2.7/site-packages/scipy/cluster/vq.py", line 786, in _kmeans2
    new_code, has_members = _vq.update_cluster_means(data, label, nc)
  File "scipy/cluster/_vq.pyx", line 347, in scipy.cluster._vq.update_cluster_means (scipy/cluster/_vq.c:4550)
TypeError: type other than float or double not supported
```

**Comment by zhanghappy123** [comment]
Hi,samarth51 and jungminchoi:
I indeed get some errors while running SV-Bay first step (main_clustering.py)on my own data,
can you give me your all test data? I wonder know why own data have some problem. 
thanks

**Comment by yimsea** [comment]
I got the same error like jungminchoi ,can some one fix this?

**Comment by kakri** [comment]
I too have been facing similar problem when trying to train the data using bag of words model. and I have got the following errors.
File "findFeatures.py", line 54, in <module>
    voc, variance = kmeans(descriptors, k, 1) 
  File "/home/anaconda2/lib/python2.7/site-packages/scipy/cluster/vq.py", line 569, in kmeans
    book, dist = _kmeans(obs, guess, thresh=thresh)
  File "/home/anaconda2/lib/python2.7/site-packages/scipy/cluster/vq.py", line 429, in _kmeans
    code_book, has_members = _vq.update_cluster_means(obs, obs_code, nc)
  File "scipy/cluster/_vq.pyx", line 340, in scipy.cluster._vq.update_cluster_means (scipy/cluster/_vq.c:4654)
TypeError: type other than float or double not supported
Can anyone comment about the solution?
